export const CompanyStatus = {
  UNVERIFIED: 'UNVERIFIED',
  COMPANY_NAME_VERIFIED: 'COMPANY_NAME_VERIFIED',
  COMPANY_DETAILS_VERIFIED: 'COMPANY_DETAILS_VERIFIED',
  REVERSE_PENNY_VERIFIED: 'REVERSE_PENNY_VERIFIED',
  VERIFIED: 'VERIFIED',
};
