export enum Access {
  USER_MANAGEMENT = 'USER_MANAGEMENT',
  DELETE_USERS = 'DELETE_USERS',
  COMPANY_DETAILS = 'COMPANY_DETAILS',
  WALLET = 'WALLET',
  BROWSE_PRODUCT = 'BROWSE_PRODUCT',
  ADD_TO_CART = 'ADD_TO_CART',
  BUY = 'BUY',
  VIEW_PAST_ORDERS = 'VIEW_PAST_ORDERS',
}
